name: "Ricebox Action"
description: "Publish Go package with Ricebox"
inputs:
  path-to-main:
    description: "Path to main.go"
    required: true
    default: "."
  invoker-package:
    description: "Package which invokes the static files"
    required: true
    default: "static"
  output-file:
    description: "Output file"
    required: true
    default: "main"
runs:
  using: "composite"
  steps:
    - name: install go.rice
      run: go install github.com/GeertJohan/go.rice
      shell: bash
    - name: install rice
      run: go install github.com/GeertJohan/go.rice/rice
      shell: bash
    - name: change directory to path-to-main
      run: cd ${{ inputs.path-to-main }}
      shell: bash
    - name: build executable
      run: go build -o ${{ inputs.output-file }}
      shell: bash
    - name: append static files
      run: rice append -i ${{ inputs.invoker-package }} --exec ${{ inputs.output-file }}
      shell: bash
